---
title: "World Development indicators Dashboard"
author: "Rocco Incardona"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Topic

The scope of this project is to build an interactive dashboard using R-Shiny and flexdashboard.
The dashboard will present some advanced visualizations on a selection of World Bank's Development indicators, covering the following areas: Environment, Economy and People. In particular, the charts will try to shed some light
on the countries, which have the strongest impact on the environment (e.g. in terms of carbon emissions or energy consumption) and try to identify which economic and social drivers could be behind those developments. 


## Data Sources

The World Development Indicators is a compilation of relevant, high-quality, and internationally comparable statistics about global development and the fight against poverty. The database contains 1,400 time series indicators for 217 economies and more than 40 country groups, with data for many indicators going back more than 50 years. The data is compiled by the World Bank using officially-recognized international sources. 

The indicators covered in this projected are described in detail on the following pages:

* Main page: https://datatopics.worldbank.org/world-development-indicators/
* Environment: https://datatopics.worldbank.org/world-development-indicators/themes/environment.html
* Economy: https://datatopics.worldbank.org/world-development-indicators/themes/economy.html
* People: https://datatopics.worldbank.org/world-development-indicators/themes/people.html

## Description of the Data

The World Development indicators used in the project have annual frequency and are available for almost 217 economies and different macro-regions. The overall dataset includes around 380.000 rows and 65 columns (including descriptions and years), but only a subset of these data will be used. In particular, the following indicators will be covered:

* Environment:
  + EN.BIR.THRD.NO	Environment: Biodiversity & protected areas	Bird species, threatened
  + EN.FSH.THRD.NO	Environment: Biodiversity & protected areas	Fish species, threatened
  + EN.HPT.THRD.NO	Environment: Biodiversity & protected areas	Plant species (higher), threatened
  + EN.MAM.THRD.NO	Environment: Biodiversity & protected areas	Mammal species, threatened
  + EN.POP.DNST	Environment: Density & urbanization	Population density (people per sq. km of land area)
  + SP.URB.TOTL.IN.ZS	Environment: Density & urbanization	Urban population (% of total population)
  + EN.ATM.CO2E.KT	Environment: Emissions	Total CO2 emissions (thousand metric tons of CO2 excluding Land-Use Change and Forestry)
  + EN.ATM.GHGT.KT.CE	Environment: Emissions	Total greenhouse gas emissions (thousand metric tons of CO2 equivalent excluding Land-Use Change and Forestry)
  + EG.ELC.FOSL.ZS	Environment: Energy production & use	Electricity production from oil, gas and coal sources (% of total)
  + EG.USE.COMM.CL.ZS	Environment: Energy production & use	Alternative and nuclear energy (% of total energy use)
  + EG.IMP.CONS.ZS	Environment: Energy production & use	Energy imports, net (% of energy use)

* Economy:
  + NY.GDP.MKTP.PP.CD	Economic Policy & Debt: Purchasing power parity	GDP, PPP (current international $)
  + NY.GDP.PCAP.PP.CD	Economic Policy & Debt: Purchasing power parity	GDP per capita, PPP (current international $)
  + NE.RSB.GNFS.ZS	Economic Policy & Debt: National accounts: Shares of GDP & other	External balance on goods and services (% of GDP)
  + NE.TRD.GNFS.ZS	Economic Policy & Debt: National accounts: Shares of GDP & other	Trade (% of GDP)
  + NV.IND.MANF.ZS	Economic Policy & Debt: National accounts: Shares of GDP & other	Manufacturing, value added (% of GDP)
  + NE.CON.PRVT.PP.CD	Economic Policy & Debt: Purchasing power parity	Households and NPISHs Final consumption expenditure, PPP (current international $)

* Society:
  + SP.POP.TOTL	Health: Population: Structure	Population, total
  + SP.POP.GROW	Health: Population: Dynamics	Population growth (annual %)
  + SP.DYN.TFRT.IN	Health: Reproductive health	Fertility rate, total (births per woman)
  + HD.HCI.OVRL	Public Sector: Policy & institutions	Human capital index (HCI) (scale 0-1)
  + IQ.CPA.GNDR.XQ	Public Sector: Policy & institutions	CPIA gender equality rating (1=low to 6=high)
  + SP.DYN.CBRT.IN	Health: Population: Dynamics	Birth rate, crude (per 1,000 people)
  + SP.DYN.CDRT.IN	Health: Population: Dynamics	Death rate, crude (per 1,000 people)
  + VC.IDP.NWCV	Public Sector: Conflict & fragility	Internally displaced persons, new displacement associated with conflict and violence (number of cases)
  + VC.IDP.NWDS	Public Sector: Conflict & fragility	Internally displaced persons, new displacement associated with disasters (number of cases)
  + VC.IDP.TOCV	Public Sector: Conflict & fragility	Internally displaced persons, total displaced by conflict and violence (number of people)

Since the data is shaped in a wide form (one indicator and country for each row and several years in the columns), data reshaping will be necessary to simplify the visualizations (i.e. creating one unique year column)

## Main charts:

The project will include eight figures: 1) choropleths 2) bar chart 3) animated map 4) line plots 5) scatter plot 6) box plot
7) proportional area and 8) Sankey diagram. A small description for three of the chart type above is provided:

1) Choropleth. Given that the dataset includes several indicators for most of the countries of the world, an interactive choropleth will be shown allowing the users to select one of the indicators described in the previous section and plot it in a world or regional map.

2) Bar chart. The idea is to display CO2 emissions ranking by country in an animated bar charts which changes over time.

3) Scatter plot. The chart will diplay the interaction between different environmental and socio-economic variables.
The user can select which variables will be displayed.


