---
title: "World Bank dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    css: styles.css
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(ggplot2)
library(shiny)

library(tictoc)
#library(WDI)
library(wbstats)
library(gganimate)


environment <- c("EN.POP.DNST", "EN.ATM.CO2E.KT", "EN.ATM.GHGT.KT.CE", "EG.ELC.FOSL.ZS")
economy <- c("NY.GDP.MKTP.PP.CD", "NY.GDP.PCAP.PP.CD", "NE.RSB.GNFS.ZS")
society <- c("SP.POP.TOTL", "SP.POP.GROW")
all_indicators <- c(environment,economy,society)

# tic()
# df <- wb_data(country = "countries_only", indicator = all_indicators, start_date = 1990, end_date = 2020)
# toc()
# dim(df)
# write.csv(df,"capstone_project\\wdi_data.csv", row.names = FALSE)
#setwd("capstone_project\\")

tic()
df <- read_csv("wdi_data.csv")
toc()
```



Page 1
======

Input{.sidebar}
----------------------------------------------------------------
### Filters

```{r}

titles_indicators <- c("Total CO2 emissions" = "EN.ATM.CO2E.KT", 
                         "Total population" = "SP.POP.TOTL", 
                         "Purchasing power parity GDP" = "NY.GDP.MKTP.PP.CD",
                         "Population growth (annual %)" = "SP.POP.GROW")    

selectInput("Indicator", "Indicator", 
            titles_indicators, 
            multiple = FALSE, selected="EN.ATM.CO2E.KT")

sliderInput("dateSel", "Date",
            min = min(df$date, na.rm = TRUE),
            max = max(df$date, na.rm = TRUE),
            value = min(df$date, na.rm = TRUE),
            step = 1,
            timeFormat = "%d %b %y",
            animate = animationOptions(interval = 500, loop = FALSE),
            sep = ""
)

# Change slider input date based on the availability of the selected indicator
observeEvent(input$Indicator, {
    df[[input$Indicator]]
  
    df_range <- df %>% select(iso2c, iso3c, country,date, as.name(input$Indicator)) %>% filter(!is.na(df[[input$Indicator]]))
    
    updateSliderInput(session, "dateSel", 
                      min = min(df_range$date,na.rm = TRUE),
                      max = max(df_range$date,na.rm = TRUE)
                      )

  })


```


Column
----------------------------------------------------------------

### <b><font face="Roboto" size="5em" color="#000000">Chart 1</font></b> 

```{r}

g <- list(projection = list(type = 'natural earth'), showland = TRUE, landcolor = toRGB("#e5ecf6")) #orthographic - 'natural earth'
t <- list(family = "Roboto",  size = 25,  color = "#25476D")
m <- list(autoexpand = TRUE, l = 25, r = 25, b = 100, t = 100, pad = 0)

renderPlotly({
  
    fig_dat_all<- df %>% select(iso3c, country, date, unname(titles_indicators))
    max_legend <- max(fig_dat_all[[input$Indicator]], na.rm = TRUE)
    min_legend <- min(fig_dat_all[[input$Indicator]], na.rm = TRUE)
    
    fig_dat_selected <- df %>% select(iso3c, country, date, unname(titles_indicators)) %>% filter(date==input$dateSel)
    title_name <- paste(names(titles_indicators)[titles_indicators == input$Indicator],input$dateSel, sep = " in ")
    
    
    plot_ly(fig_dat_selected, type='choropleth', 
            locations=fig_dat_selected$iso3c, 
            z = fig_dat_selected[[input$Indicator]], 
            text = fig_dat_selected$country, 
            colorscale = ifelse(input$Indicator == "SP.POP.GROW", "Viridis", "Blues"),
            reversescale = T,
            height = 750,
            zmax = max_legend,
            zmin = min_legend) %>% 
      layout(geo = g, title = title_name , font=t, margin = m, plot_bgcolor = "#e5ecf6") 
  
  })

```

Page 2
======

Column
-----------------------------------------------------------------------

### <b><font face="Roboto" size="5em" color="#000000">Chart 2</font></b> 

```{r}

renderImage({
  outfile <- tempfile(fileext='.gif')
  
  # all_data<-df %>% select(iso3c, country,date, EN.ATM.CO2E.KT) #%>% filter(date==2000) %>% slice_max(EN.ATM.CO2E.KT, n = 10)
  # 
  # top_10 <- all_data %>% 
  #   group_by(date) %>% 
  #   slice_max(order_by = EN.ATM.CO2E.KT, n=10) %>% 
  #   mutate(ranking = rank(-EN.ATM.CO2E.KT)) %>% 
  #   ungroup()
  # 
  # p <- top_10 %>%
  #   ggplot(aes(x = -ranking,y = EN.ATM.CO2E.KT, group = country)) +
  #   geom_tile(aes(y = EN.ATM.CO2E.KT / 2, height = EN.ATM.CO2E.KT, fill = country), width = 0.9) +
  #   scale_fill_brewer(palette = "Paired") +
  #   geom_text(aes(label = country), hjust = "right", colour = "black", fontface = "bold", nudge_y = -100000) +
  #   geom_text(aes(label = scales::comma(EN.ATM.CO2E.KT)), hjust = "left", nudge_y = 100000, colour = "grey30") +
  #   coord_flip(clip="off") +
  #   scale_fill_discrete(guide = 'none')+
  #   scale_x_discrete("") +
  #   scale_y_continuous("",labels=scales::comma) +
  #   hrbrthemes::theme_ipsum(plot_title_size = 32, subtitle_size = 24, caption_size = 20, base_size = 20) +
  #   theme(panel.grid.major.y=element_blank(),
  #         panel.grid.minor.x=element_blank(),
  #         #legend.position = c(0.4, 0.2),
  #         plot.margin = margin(1,1,1,2,"cm"),
  #         axis.text.y=element_blank()) +
  #   # gganimate code to transition by year:
  #   transition_time(date) +
  #   ease_aes('cubic-in-out') +
  #   labs(title='World largest polluters',
  #        subtitle='Tons of CO2 emissions in {round(frame_time,0)}',
  #        caption='Source: World Bank
  # Rocco Incardona / @incardo')
  # 
  # animate(p, nframes = 750, fps = 25, end_pause = 50, width = 1250, height = 750)
  # 
  # anim_save("outfile.gif", animation = last_animation())
  
  # Return a list containing the filename
  list(src = "outfile.gif",
       contentType = 'image/gif'
       # width = 400,
       # height = 300,
       # alt = "This is alternate text"
)}, deleteFile = FALSE)


```


Page 3
======

Input{.sidebar}
----------------------------------------------------------------
### Filters

```{r}
#selectInput("State", "State", dat$st_name, multiple = TRUE, selected=dat$st_name)

selectInput("Indicator1", "Indicator1", 
            titles_indicators, 
            multiple = FALSE, selected="EN.ATM.CO2E.KT")

selectInput("Indicator2", "Indicator2", 
            titles_indicators, 
            multiple = FALSE, selected="NY.GDP.MKTP.PP.CD")


sliderInput("dateSel2", "Date",
            min = 1990, #min(df$date, na.rm = TRUE),
            max = 2018, #max(df$date, na.rm = TRUE),
            value = min(df$date, na.rm = TRUE),
            step = 1,
            timeFormat = "%d %b %y",
            animate = animationOptions(interval = 500, loop = FALSE),
            sep = ""
)

```

Column
----------------------------------------------------------------
### <b><font face="Roboto" size="5em" color="#000000">Chart 3</font></b> 

```{r}
# renderText({ 
#     scatter_data_all <- df %>% select(iso2c, iso3c, country, date, unname(titles_indicators))
#     max_x <- log(max(scatter_data_all[[input$Indicator1]]+100, na.rm = TRUE))
#     min_x <- log(min(scatter_data_all[[input$Indicator1]]+100, na.rm = TRUE))
#     max_y <- log(max(scatter_data_all[[input$Indicator2]]+100, na.rm = TRUE))
#     min_y <- log(min(scatter_data_all[[input$Indicator2]]+100, na.rm = TRUE))
#     print(c(max_x, min_x, max_y, min_y, min(scatter_data_all[[input$Indicator2]], na.rm = TRUE)))})

renderPlotly({
  
    scatter_data <- df %>% select(iso2c, iso3c, country, date, unname(titles_indicators)) %>% filter(date==input$dateSel2)
    title_scatter <- paste(names(titles_indicators)[titles_indicators == input$Indicator1], " vs ",
                        names(titles_indicators)[titles_indicators == input$Indicator2],
                        "in",
                        input$dateSel2, sep = " ")
    
    #fv <- scatter_data %>% filter(!is.na(scatter_data[[input$Indicator1]]) & !is.na(scatter_data[[input$Indicator2]])) %>% 
    #  lm(scatter_data[[input$Indicator1]] ~ scatter_data[[input$Indicator2]],.) %>% fitted.values()
    
    scatter_data_all <- df %>% select(iso2c, country, date, unname(titles_indicators))
    max_x <- log(max(scatter_data_all[[input$Indicator1]]+100, na.rm = TRUE))
    min_x <- log(min(scatter_data_all[[input$Indicator1]]+100, na.rm = TRUE))
    max_y <- log(max(scatter_data_all[[input$Indicator2]]+100, na.rm = TRUE))
    min_y <- log(min(scatter_data_all[[input$Indicator2]]+100, na.rm = TRUE))
    corr_x <- ifelse(input$Indicator1=="SP.POP.GROW", 0.005, 0.1)
    corr_y <- ifelse(input$Indicator2=="SP.POP.GROW", 0.005, 0.1)

    plot_ly(data = scatter_data, x = log(scatter_data[[input$Indicator1]]+100), y = log(scatter_data[[input$Indicator2]]+100),
            text = ~country) %>% 
          layout(autosize = F, width = 900, height = 750, margin = m,
                 xaxis = list(title = paste("Log of ", names(titles_indicators)[titles_indicators == input$Indicator1]),
                              range = list(min_x-min_x*corr_x, max_x+min_x*corr_x)),
                 yaxis = list(title = paste("Log of ", names(titles_indicators)[titles_indicators == input$Indicator2]),
                              range = list(min_y-min_y*corr_y, max_y+min_y*corr_y)),
                 title = list(text = title_scatter, font=t)) %>%
          add_text(text=~iso2c, textposition="top center", mode = "markers+text",showlegend = F)
      
            #hovertemplate = 'Country: %{scatter_data$country}<extra></extra>'
           #%>% 
    #add_trace(x = scatter_data[[input$Indicator2]], y = fv, mode = "lines") %>%
    #layout(showlegend = F)
    
    # plot_ly(fig_dat_selected, type='choropleth', 
    #         locations=fig_dat_selected$iso3c, 
    #         z = fig_dat_selected[[input$Indicator]], 
    #         text = fig_dat_selected$country, 
    #         colorscale = ifelse(input$Indicator == "SP.POP.GROW", "Viridis", "Blues"),
    #         reversescale = T,
    #         height = 750,
    #         zmax = max_legend,
    #         zmin = min_legend) %>% 
    #   layout(geo = g, title = title_name , font=t, margin = m, plot_bgcolor = "#e5ecf6") 

  })


```

Page 4
======

Input{.sidebar}
----------------------------------------------------------------
### Filters

```{r}
#selectInput("State", "State", dat$st_name, multiple = TRUE, selected=dat$st_name)

selectInput("country_sel", "Country", 
            unique(df$country), 
            multiple = FALSE, selected="Canada")


sliderInput("dateSel3", "Date",
            min = 1990, #min(df$date, na.rm = TRUE),
            max = 2018, #max(df$date, na.rm = TRUE),
            value = min(df$date, na.rm = TRUE),
            step = 1,
            timeFormat = "%d %b %y",
            animate = animationOptions(interval = 500, loop = FALSE),
            sep = ""
)

```

Row
-------------------------------------
    
### <b><font face="Roboto" size="5em" color="#000000">Chart 4</font></b> 
    
```{r}

renderPlot({df %>% filter(country==input$country_sel) %>% 
            ggplot(aes(x = date,y = EN.ATM.CO2E.KT))+geom_line()
          })


```
 
### <b><font face="Roboto" size="5em" color="#000000">Chart 5</font></b> 
    
```{r}
renderPlot({df %>% filter(country==input$country_sel) %>% 
            ggplot(aes(x = date,y = SP.POP.TOTL))+geom_line()
          })
``` 

Row
-------------------------------------
    
### <b><font face="Roboto" size="5em" color="#000000">Chart 6</font></b> 
    
```{r}
renderPlot({df %>% filter(country==input$country_sel) %>% 
            ggplot(aes(x = date,y = NY.GDP.MKTP.PP.CD))+geom_line()
          })
```
    
### <b><font face="Roboto" size="5em" color="#000000">Chart 7</font></b> 

```{r}
renderPlot({df %>% filter(country==input$country_sel) %>% 
            ggplot(aes(x = date,y = SP.POP.GROW))+geom_line()
          })
```




